import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Roboto_Flex as Roboto } from "next/font/google";

import { QueryProvider } from "@/providers/query-provider";

import "./globals.css";

const roboto = Roboto({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-roboto",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="pt-BR" className={`${roboto.variable} antialiased`}>
			<body className="min-h-screen" suppressHydrationWarning>
				<QueryProvider>{children}</QueryProvider>
			</body>
		</html>
	);
}
